meta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('therapists.urls', namespace = 'therapists')),
]

therapists/urls.py
from django.urls import re_path, path

from . import views

app_name = 'therapists'

urlpatterns = [
	path('', views.therapists, name='therapists'),
	re_path(r'^therapist/(?P<pk>\w+)/$', views.therapist, name='therapist'),
]

therapists/models.py
from django.db import models

# Create your models here.


class Therapist(models.Model):
	rec_id = models.CharField(max_length=800, primary_key=True)
	photo = models.TextField()
	FIO = models.CharField(max_length=800)
	methods = models.JSONField()
	
	class Meta:
		db_table = 'therapist'
	
	

therapists/views.py
from django.shortcuts import render

# Create your views here.

from .models import Therapist


def therapists(request):
	therapists = Therapist.objects.all()
	print("num of therapists: ", len(therapists))
	return render(request, 'therapists.html', {'therapists': therapists})

def therapist(request, pk):
	try:
		therapist = Therapist.objects.get(pk=pk)
	except Therapist.DoesNotExist:
		return render(request, 'therapist_404.html', {})

	return render(request, 'therapist.html', {'therapist': therapist})

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	
	<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
	<meta name ="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>


 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Django Library App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>


	
    <div class="container">
        <div class="row spacer"></div>
        <div class="row offset-2">
            <div class="col-12">
                {% block container %}
				
				

				
                {% endblock %}
            </div>
        </div>
    </div>

{% block custom_js %}{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.6.0/umd/popper.min.js" integrity="sha512-BmM0/BQlqh02wuK5Gz9yrbe7VyIVwOzD1o40yi1IsTjriX/NGF37NyXHfmFzIlMmoSIBXgqDiG1VNU6kB5dBbA==" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

templates/therapist.html
{% extends 'base.html' %}

{% block container %}


<div id="parent">

<div v-bind:style="left_block">
<img v-bind:style="avatar" src={{ therapist.photo }}>
</div>

<div v-bind:style="right_block">

<h3>
{{ therapist.FIO }}
</h3>

<h5>Методы:</h5>

{% for method in therapist.methods %}

<li v-bind:style="method">{{ method }}</li>

{% endfor %}

</div>

</div>
	
{% block custom_js %}
<script>
var app = new Vue(
{
el: "#parent",
data: {
left_block: {
position:'absolute',
top: 0,
left: 0,
width: 'relative',
marginTop: '5%',
},
right_block:{
position:'absolute',
top: 0,
right: 0,
width: '65%',
marginTop: '5%',
},
avatar:{
objectFit: 'cover',
border:'5px solid rgba(17, 107, 242, 1)',
width: '300px',
height: '400px',
},
method:{
display: 'inline-block',
height: '50px',
background: 'silver',
margin: '2px',
padding: '12px',
fontSize: '16px',
textAlign: 'center',
},
},
}
);

</script>
{% endblock %}
{% endblock %}

templates/therapist_404.html
{% extends 'base.html' %}

{% block container %}

<h2>Такого терапевата уже нет.</h2>

{% endblock %}

templates/therapists.html
{% extends 'base.html' %}

{% block container %}


{% for therapist in therapists %}


<li><a href="{% url 'therapists:therapist' therapist.rec_id %}">{{ therapist.FIO }}</a></li>

{% endfor %}

{% endblock %}